spring:
  application:
    name: baiye-ai-agent
  profiles:
    active: local
  ai:
    mcp:
      client:
        enabled: true
#        sse:
#          connections:
#            server1:
#              url: http://localhost:8127
        stdio:
          enabled: true
          servers-configuration: classpath:mcp-servers.json
#  Spring AI调用阿里dashscope
#  application:
#    name: spring-ai-alibaba-qwq-chat-client-example
#  ai:
#    dashscope:
#      api-key: 你的 API Key
#      chat:
#        options:
#          model: qwen-plus 要调用的模型名称
# Spring AI调用ollama
#  ai:
#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        model: gemma3:1b # 自己下载的模型名称
# PgVector向量存储，阿里云购买
#  datasource:
#    url: jdbc:postgresql://改为你的公网地址/yu_ai_agent
#    username: 改为你的用户名
#    password: 改为你的密码
#  ai:
#    vectorstore:
#      pgvector:
#        index-type: HNSW   # 指定创建索引的算法类型。
#        distance-type: COSINE_DISTANCE  # 指定计算向量之间相似度的方法，这里使用的是余弦距离。
#        dimensions: 1536  # 指定向量维度。
#        max-document-batch-size: 10000 # 最大文档批处理大小。
#        initialize-schema: true   #  自动建表
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.baiye.baiyeaiagent.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
# searchApi
#search-api:
#  api-key: 你的 API Key
logging:
  level:
    org.springframework.ai: DEBUG



